# Generated by Django 4.2.16 on 2024-11-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_rename_avatar_profile_avatar_url'),
        ('chat', '0002_rename_sender_message_user_message_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.match'),
        ),
    ]
