# Generated by Django 4.2.16 on 2024-11-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_rename_avatar_profile_avatar_url"),
        ("chat", "0004_alter_message_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="match",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="conversation", to="main_app.match"),
        ),
    ]
