version: "3.8"
name: "padel_connect_dev"

services:
  api:
    extends:
      file: common.yml
      service: api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    command: python manage.py runserver 0.0.0.0:${API_PORT}
    volumes:
      - ../:/app
      - ../logs:/app/logs
      - ../mediafiles:/mediafiles
    ports:
      - ${API_PORT}:${API_PORT}
    # depends_on:
    #   - db
    networks:
      - local
    secrets:
      - db_password
      - api_email_host_password
      - api_secret_key
      - push_notif_token

  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - local
    secrets:
      - db_password

  redis:
    extends:
      file: common.yml
      service: redis
    networks:
      - local
    
  celery_worker:
    extends:
      service: api
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    ports: !reset []
    networks:
      - local

  celery_beat:
    extends:
      service: api
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
    ports: !reset []

    networks:
      - local

  adminer:
    extends:
      file: common.yml
      service: adminer
    networks:
      - local

networks:
  local:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  api_email_host_password:
    file: ./secrets/api_email_host_password.txt
  api_secret_key:
    file: ./secrets/api_secret_key.txt
  push_notif_token:
    file: ./secrets/push_notif_token.txt

volumes:
  db_data:
