version: "3.8"

services:
  api:
    extends:
      file: common.yml
      service: api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    volumes:
      - api_data:/app
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    environment:
      - DEBUG=0
    expose:
      - ${API_PORT}
    depends_on:
      - db
    networks:
      - local
    secrets:
      - db_password
      - api_email_host_password
      - api_secret_key

  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - local
    secrets:
      - db_password

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - ${API_PORT}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    environment:
      API_PORT: ${API_PORT}
    networks:
      - local
    depends_on:
      - api

networks:
  local:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  api_email_host_password:
    file: ./secrets/api_email_host_password.txt
  api_secret_key:
    file: ./secrets/api_secret_key.txt

volumes:
  db_data:
  api_data:
  static_volume:
  media_volume:
