version: "3.8"
name: "padel_connect_prod"

services:
  api:
    extends:
      file: common.yml
      service: api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:${API_PORT}
    volumes:
      - api_data:/app
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    expose:
      - ${API_PORT}
    # depends_on:
    #   - db
    #   - nginx
    #   - redis
    networks:
      - local
    secrets:
      - db_password
      - api_email_host_password
      - api_secret_key
      - push_notif_token

  ws:
    extends:
      service: api
    container_name: ws
    command: daphne backend.asgi:application --bind 0.0.0.0 -p ${WS_PORT}
    expose:
      - ${WS_PORT}
    networks:
      - local

  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - local
    secrets:
      - db_password

  redis:
    extends:
      file: common.yml
      service: redis
    networks:
      - local
      
  celery_worker:
    extends:
      service: api
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    networks:
      - local

  celery_beat:
    extends:
      service: api
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
    networks:
      - local

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - ${API_PORT}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    environment:
      API_PORT: ${API_PORT}
      WS_PORT: ${WS_PORT}
    networks:
      - local

networks:
  local:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  api_email_host_password:
    file: ./secrets/api_email_host_password.txt
  api_secret_key:
    file: ./secrets/api_secret_key.txt
  push_notif_token:
    file: ./secrets/push_notif_token.txt

volumes:
  db_data:
  api_data:
  static_volume:
  media_volume:
