# Generated by Django 4.2.16 on 2024-10-17 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_profile_avatar_url_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complex',
            options={'verbose_name': 'Complex', 'verbose_name_plural': 'Complexes'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='favoriteuser',
            options={'verbose_name': 'Favorite user', 'verbose_name_plural': 'Favorite users'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchfilter',
            options={'verbose_name': 'Match filter', 'verbose_name_plural': 'Match filters'},
        ),
        migrations.AlterModelOptions(
            name='matchrequest',
            options={'verbose_name': 'Match request', 'verbose_name_plural': 'Match requests'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AlterField(
            model_name='matchfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
