# Generated by Django 4.2.16 on 2024-10-17 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_complex_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteuser',
            name='favorite_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchfilter',
            name='level_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='matchfilter',
            name='level_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
