# Generated by Django 4.2.16 on 2024-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
