# Generated by Django 4.2.16 on 2024-10-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_customuser_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='push_token',
        ),
    ]
