# Generated by Django 4.2.16 on 2024-10-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_profile_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_MESSAGE', 'New Message'), ('NEW_MATCH', 'New Match'), ('NEW_MATCH_REQUEST', 'New Match Request'), ('MATCH_REQUEST_RESPONSE_ACCEPTED', 'Match Request Response Accepted'), ('MATCH_REQUEST_RESPONSE_REFUSED', 'Match Request Response Refused')], default='NEW_MESSAGE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
