# Generated by Django 4.2.16 on 2024-10-26 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_notification_type_alter_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfilter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_filter', to=settings.AUTH_USER_MODEL),
        ),
    ]
