# Generated by Django 4.2.16 on 2024-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_matchfilter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'En'), ('FR', 'Fr')], max_length=10, null=True),
        ),
    ]
