# Generated by Django 4.2.16 on 2024-10-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
        migrations.AddField(
            model_name='notification',
            name='associated_data',
            field=models.JSONField(null=True),
        ),
    ]
