# Generated by Django 4.2.16 on 2024-11-01 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_new_match_notification_enabled',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_new_message_notification_enabled',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_new_match_notification_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_new_message_notification_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'En'), ('FR', 'Fr')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='FavoriteUser',
        ),
    ]
