# Generated by Django 4.2.16 on 2024-11-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_profile_is_new_match_notification_enabled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchRequest',
        ),
    ]
