# Generated by Django 4.2.16 on 2024-11-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_delete_matchrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='avatar_url',
        ),
    ]
