# Generated by Django 4.2.16 on 2024-11-16 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_rename_avatar_profile_avatar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACCEPTED", "Accepted"), ("REFUSED", "Refused"), ("PENDING", "Pending")], default="PENDING", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="main_app.match")),
                (
                    "team",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="match_participations", to="main_app.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "MatchPlayer",
                "verbose_name_plural": "MatchPlayers",
            },
        ),
        migrations.CreateModel(
            name="TeamInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("ACCEPTED", "Accepted"), ("REFUSED", "Refused"), ("PENDING", "Pending")], default="PENDING")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="team_invites", to=settings.AUTH_USER_MODEL),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="main_app.team")),
            ],
            options={
                "unique_together": {("team", "invited_user")},
            },
        ),
    ]
