# Generated by Django 4.2.16 on 2024-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_team_matchplayer_teaminvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="defense_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="offense_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="service_level",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
