# Generated by Django 4.2.16 on 2024-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_alter_profile_defense_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="type",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="type",
        ),
        migrations.AddField(
            model_name="match",
            name="is_competition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="is_competition",
            field=models.BooleanField(default=False),
        ),
    ]
