# Generated by Django 4.2.16 on 2024-11-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_remove_match_type_remove_tournament_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="is_competition",
            new_name="is_competitive",
        ),
        migrations.RenameField(
            model_name="tournament",
            old_name="is_competition",
            new_name="is_competitive",
        ),
    ]
