# Generated by Django 4.2.16 on 2024-11-25 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0022_rename_is_competition_match_is_competitive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="match",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="teams", to="main_app.match"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="status",
            field=models.CharField(
                choices=[("ACCEPTED", "Accepted"), ("REFUSED", "Refused"), ("PENDING", "Pending"), ("CREATING", "Creating")], default="CREATING"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="status",
            field=models.CharField(
                choices=[("ACCEPTED", "Accepted"), ("REFUSED", "Refused"), ("PENDING", "Pending"), ("CREATING", "Creating")], default="PENDING"
            ),
        ),
        migrations.DeleteModel(
            name="MatchPlayer",
        ),
    ]
