# Generated by Django 4.2.16 on 2024-11-27 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0023_team_match_team_status_team_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teaminvite",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="user",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="participants", to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="main_app.team"),
        ),
        migrations.AlterUniqueTogether(
            name="teaminvite",
            unique_together={("team", "user")},
        ),
        migrations.RemoveField(
            model_name="teaminvite",
            name="invited_user",
        ),
    ]
