# Generated by Django 4.2.16 on 2024-11-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0024_alter_teaminvite_unique_together_teaminvite_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="is_reserved",
            field=models.BooleanField(default=False),
        ),
    ]
