# Generated by Django 4.2.16 on 2024-12-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0026_alter_team_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teaminvite",
            options={"ordering": ["id"]},
        ),
    ]
