# Generated by Django 4.2.16 on 2024-12-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0027_alter_teaminvite_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="status",
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="status",
            field=models.CharField(choices=[("ACCEPTED", "Accepted"), ("REFUSED", "Refused"), ("PENDING", "Pending")], default="PENDING"),
        ),
    ]
