# Generated by Django 4.2.16 on 2024-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0028_remove_team_status_alter_teaminvite_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
