# Generated by Django 4.2.16 on 2024-12-12 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0031_alter_match_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["id"], "verbose_name": "Team", "verbose_name_plural": "Teams"},
        ),
        migrations.AlterModelOptions(
            name="tournament",
            options={"ordering": ["-datetime"], "verbose_name": "Tournament", "verbose_name_plural": "Tournaments"},
        ),
        migrations.CreateModel(
            name="MatchArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime", models.DateTimeField()),
                ("level", models.FloatField()),
                ("is_competitive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("complex", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="main_app.complex")),
                ("user", models.ManyToManyField(related_name="archived_matches", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
