# Generated by Django 4.2.16 on 2024-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0032_alter_team_options_alter_tournament_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matcharchive",
            options={"ordering": ["-datetime"]},
        ),
        migrations.AddField(
            model_name="matcharchive",
            name="is_open_to_all_level",
            field=models.BooleanField(default=False),
        ),
    ]
