# Generated by Django 4.2.16 on 2024-12-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0034_matcharchive_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="complex",
            name="four_padel_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
