# Generated by Django 4.2.16 on 2024-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0035_complex_four_padel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="four_padel_field_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="is_decisive_point",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="is_super_tie_break",
            field=models.BooleanField(default=False),
        ),
    ]
