# Generated by Django 4.2.16 on 2024-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0040_alter_customuser_is_new_match_notification_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("NEW_MESSAGE", "New Message"),
                    ("NEW_MATCH", "New Match"),
                    ("NEW_MATCH_INVITATION", "New Match Invitation"),
                    ("MATCH_REQUEST_RESPONSE_ACCEPTED", "Match Request Response Accepted"),
                    ("MATCH_REQUEST_RESPONSE_REFUSED", "Match Request Response Refused"),
                    ("NEW_PLAYERS", "New Players"),
                    ("INVITATION_RESPONSE", "Invitation Response"),
                ],
                max_length=50,
            ),
        ),
    ]
