# Generated by Django 4.2.16 on 2024-12-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0042_alter_complex_options_alter_match_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matcharchive",
            name="four_padel_field_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="matcharchive",
            name="four_padel_field_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="four_padel_field_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="four_padel_field_name",
            field=models.CharField(null=True),
        ),
    ]
