# Generated by Django 4.2.16 on 2025-01-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0043_matcharchive_four_padel_field_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-id"], "verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="four_padel_token",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("NEW_MESSAGE", "New Message"),
                    ("NEW_MATCH", "New Match"),
                    ("NEW_MATCH_INVITATION", "New Match Invitation"),
                    ("MATCH_REQUEST_RESPONSE_ACCEPTED", "Match Request Response Accepted"),
                    ("MATCH_REQUEST_RESPONSE_REFUSED", "Match Request Response Refused"),
                    ("NEW_PLAYERS", "New Players"),
                    ("INVITATION_RESPONSE", "Invitation Response"),
                    ("MATCH_SHARE", "Match Share"),
                ],
                max_length=50,
            ),
        ),
    ]
