# Generated by Django 4.2.16 on 2025-01-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0045_match_four_padel_reservation_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="four_padel_reservation_id",
            new_name="four_padel_booking_id",
        ),
    ]
