# Generated by Django 4.2.16 on 2025-01-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0046_rename_four_padel_reservation_id_match_four_padel_booking_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="is_reserved",
            new_name="is_booked",
        ),
    ]
