# Generated by Django 4.2.16 on 2025-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0047_rename_is_reserved_match_is_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="four_padel_price",
            field=models.FloatField(default=80),
            preserve_default=False,
        ),
    ]
