# Generated by Django 4.2.16 on 2025-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0048_match_four_padel_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="four_padel_price",
        ),
        migrations.AddField(
            model_name="match",
            name="four_padel_field_price",
            field=models.FloatField(null=True),
        ),
    ]
