# Generated by Django 4.2.16 on 2025-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0049_remove_match_four_padel_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="four_padel_field_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="match",
            name="four_padel_field_price",
            field=models.FloatField(),
        ),
    ]
