# Generated by Django 4.2.16 on 2025-01-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0050_alter_match_four_padel_field_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["datetime"], "verbose_name": "Match", "verbose_name_plural": "Matches"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="four_padel_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
