# Generated by Django 4.2.16 on 2025-01-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0051_alter_match_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complex",
            name="four_padel_latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="complex",
            name="four_padel_longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
    ]
