# Generated by Django 4.2.16 on 2025-01-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0053_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="elo",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
