# Generated by Django 4.2.16 on 2025-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0054_profile_elo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="elo",
            field=models.FloatField(default=1),
        ),
    ]
