# Generated by Django 4.2.16 on 2025-01-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0055_alter_profile_elo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="level",
            new_name="elo",
        ),
    ]
