# Generated by Django 4.2.16 on 2025-01-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0056_rename_level_match_elo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matcharchive",
            old_name="level",
            new_name="elo",
        ),
    ]
