# Generated by Django 4.2.16 on 2025-01-17 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0057_rename_level_matcharchive_elo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="match",
        ),
        migrations.AddField(
            model_name="matcharchive",
            name="score",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MatchArchiveTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "user_1",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="user_1", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "user_2",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="user_2", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matcharchive",
            name="team_1",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="team_1", to="main_app.matcharchiveteam"
            ),
        ),
        migrations.AddField(
            model_name="matcharchive",
            name="team_2",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="team_2", to="main_app.matcharchiveteam"
            ),
        ),
    ]
