# Generated by Django 4.2.16 on 2025-01-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0058_remove_score_match_matcharchive_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matcharchive",
            name="user",
        ),
    ]
