# Generated by Django 4.2.16 on 2025-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0068_alter_matcharchive_team_1_alter_matcharchive_team_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="sets_team_1",
        ),
        migrations.RemoveField(
            model_name="score",
            name="sets_team_2",
        ),
        migrations.RemoveField(
            model_name="score",
            name="tie_breaks_team_1",
        ),
        migrations.RemoveField(
            model_name="score",
            name="tie_breaks_team_2",
        ),
        migrations.AddField(
            model_name="score",
            name="sets",
            field=models.JSONField(default={"team_1": [], "team_2": []}),
        ),
        migrations.AddField(
            model_name="score",
            name="tie_breaks",
            field=models.JSONField(default={"team_1": [], "team_2": []}),
        ),
    ]
