# Generated by Django 4.2.16 on 2025-01-21 14:06

from django.db import migrations, models
import main_app.models.match


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0071_matcharchive_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="score_data",
            field=models.JSONField(default=main_app.models.match.default_score_data),
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
