create type "public"."tournament_type" as enum ('LEISURE', 'COMPETITION');

create table "public"."tournaments" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "description" text not null,
    "complex_id" bigint,
    "datetime" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "type" tournament_type not null
);


alter table "public"."tournaments" enable row level security;

CREATE UNIQUE INDEX tournaments_pkey ON public.tournaments USING btree (id);

alter table "public"."tournaments" add constraint "tournaments_pkey" PRIMARY KEY using index "tournaments_pkey";

alter table "public"."tournaments" add constraint "public_tournaments_complex_id_fkey" FOREIGN KEY (complex_id) REFERENCES complexes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tournaments" validate constraint "public_tournaments_complex_id_fkey";

grant delete on table "public"."tournaments" to "anon";

grant insert on table "public"."tournaments" to "anon";

grant references on table "public"."tournaments" to "anon";

grant select on table "public"."tournaments" to "anon";

grant trigger on table "public"."tournaments" to "anon";

grant truncate on table "public"."tournaments" to "anon";

grant update on table "public"."tournaments" to "anon";

grant delete on table "public"."tournaments" to "authenticated";

grant insert on table "public"."tournaments" to "authenticated";

grant references on table "public"."tournaments" to "authenticated";

grant select on table "public"."tournaments" to "authenticated";

grant trigger on table "public"."tournaments" to "authenticated";

grant truncate on table "public"."tournaments" to "authenticated";

grant update on table "public"."tournaments" to "authenticated";

grant delete on table "public"."tournaments" to "service_role";

grant insert on table "public"."tournaments" to "service_role";

grant references on table "public"."tournaments" to "service_role";

grant select on table "public"."tournaments" to "service_role";

grant trigger on table "public"."tournaments" to "service_role";

grant truncate on table "public"."tournaments" to "service_role";

grant update on table "public"."tournaments" to "service_role";

create policy "Tournaments are viewable by everyone"
on "public"."tournaments"
as permissive
for select
to public
using (true);




