name: EAS Build

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Profile"
        type: choice
        default: preview
        required: true
        options:
          - local
          - preview
          - production
      submit:
        description: "Submit to Store"
        type: boolean
        required: true
        default: false

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "app"

      - name: 📦 Install Project Dependencies
        run: yarn install --frozen-lockfile
        working-directory: app

      - name: 📦 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: yarn
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📢 EAS Build
        run: eas build -e ${{ inputs.profile }} -p ios --non-interactive --no-wait
        working-directory: app
        if: ${{ inputs.profile == 'local' || inputs.profile == 'preview' || !inputs.submit }}

      - name: 📢 EAS Build and Submit
        run: eas build -e ${{ inputs.profile }} -p ios --non-interactive --no-wait --auto-submit
        working-directory: app
        if: ${{ inputs.submit && inputs.profile == 'production' }}
