name: EAS Update

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Channel"
        type: choice
        default: preview
        required: true
        options:
          - preview
          - production
      message:
        description: "Message"
        type: string
        default: ""
        required: true

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "app"

      - name: 📦 Install Project Dependencies
        run: yarn install --frozen-lockfile
        working-directory: app

      - name: 📦 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: yarn
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📢 EAS Update
        run: eas update --channel ${{ inputs.channel }} --message "${{ inputs.message }}" --non-interactive
        working-directory: app
